### ISSUE TITLE
Add 'Mystic Clovers' to options

### ISSUE THREAD

**Issue by SamWolfs** [fast-farming-community/public#4]

**Comment by c0rn1x** [comment]
Mystic Clover opportunity cost columns will appear in
- Drizzlewood Reward Track
- WvW Reward Track
- Festival Weekly Vendors (Lunar New Year
- Chest of Loyalty
- Icebrood Bags (XYZ Legion Reward Boxes)

**Comment by c0rn1x** [comment]
**Standardized Headers**
`Mystic Clover Buy Profit`
`Mystic Clover Sell Profit`
`Mystic Clover Buy Profit w/ SS`
`Mystic Clover Sell Profit w/ SS`


these headers represent values without including mystic clovers
