### ISSUE TITLE
Merge sidebar categories to increase menu readability

### ISSUE THREAD

**Issue by Arckange007** [fast-farming-community/public#44]
Merge various pages into single, tabbed pages of the same category (Dungeon currencies, LWS3, LWS4, etc.). This will help de-clutter the sidebar menu and increase its readability.

Possible merges:
- Dungeons currencies
- Season 2 currencies (Geodes, Bandit Crests)
- Season 3 currencies 
- Season 4 currencies
- IBS currencies (Chili, Eternal Ice, Eitrite Ingots, Prophet Crystals?)
- HoT maps currencies
- Raid currencies

Some good suggestions: https://discord.com/channels/587288441532710927/735925569954512966/881166644158812181

**Comment by c0rn1x** [comment]
requires a discussion / closing this for now until we gathered more information
