### ISSUE TITLE
Rework Sprit Shard to show Per Conversion / Per Spirit Shard and Crafting Material in Global Settings

### ISSUE THREAD

**Issue by SamWolfs** [fast-farming-community/public#9]
I don't even...

**Comment by c0rn1x** [comment]
Local Button implementation to sort out `Per Conversion` and `Per Spirit Shard Columns`.

Columns are missing implementation of Buy / Sell Order.

**Comment by fast-farming-community** [comment]
refactored spirit shard conversions
